---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUVyxYInsKd4S59vVH3GIKkXDcPWswDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMDIzMTMwOTAwWhcNMjQxMDIxMTMwOTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AMY5BVGg8llfDGkSz7n73dFsfLBOKqmzZDQMvQiZnYUQLxL9tCnyM1XYZqWEFC+y
    pDekkirUQD4IiTVM8q2L0VjHudefnMUOtYg1moSiEQghldsbevexb9JPA2TwEQv7
    MEZ4xYS0M7CVj1Kg22wfGkbfy+XkQ97bN8uxsOvGXkupOx68qKhEJNSbbhiew6VZ
    vmArO8n41W7BfYbTiC+GezHzSd4EYczSCiNOQS/AgbdWLrWajx8yj/73KIWaqgiQ
    bYVwgIr1X98DZz8fZ44W/IPWFDZArYmgxSrALQ75U7Dg5kk44T5UFI7YRFjf1JgC
    iVD9mHjY5Ufb89V4spC1ZzCZobFxuV0T6TP9wfHoRO4QbBtyPfl91A7RNyKE0Epb
    +7LCEew5u45FZGHNZl2Rep9xVZm1RFIG3RyYkhufClNVdjyOqIpxmW9BE3vXcB4U
    Pp+qvHYkMIoB6+zZOvYySmO1HbIDfaRuqmyFFj8DWdO8mD9A9JNF+aojZc6B0H0c
    g0zjB+wx1Y4nl75H+rDoHFy7eY8Vb5LKO06Jt3+jFk7SyTjlCU6+8h1e7ZMTeklq
    cqwg3QeLaiDyvfxN0pFsIYMHpaIuxen+YTO45cQ7k9PVGLTMXaaGd/+bhMO14cH5
    AbcUMGzOVE2gfvCoh7XcU/8xbUoSNxRt3aF58lvdh+VRAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTcCAo6uT2iM4sM
    zIG3c0NuGAdhHTANBgkqhkiG9w0BAQ0FAAOCAgEAvCvNlrYCadO4gaferzQma31z
    JV5rihDXBkOBxH8xVcCxjkZq/WLbco1gxIYfh6gfUwlZbFaSKD1MQSTUev83omuP
    xch2LiRSKOSQTIQ3T9KixaMxzmfsOGRRqJNYYiPsLrAxIVrG9kMECcXRZlbq0o1J
    Ujyl4Xm49Y+TC3HWlj3WEuy+Wht0q+4al2Y+TTmz5KUBfqL2bdpVrDS/K95hv/id
    kDXJY1372twZXHAYVnTHPpcS7uCru08tmBsGM9knMOky720ZLDsxro2f9d2r5a7B
    qcaGg09jbP7Jz3yVaPbDRGeu4J9zXhCQeNpy3zCkF6+eEPZu5/ehEFDCkWnkVoRC
    F6qMbVQw2QXBrFa460o4uCWKfYHdPLJLxgu6jqzvy+QFfV6xh/kikYl8QmpdHi5E
    6s+QiV1LZLzdwasJxns9oAW3J18sOnwP5GeH0J+J5v+tpcwsP0Liq2nRENctDMFf
    mhFJ+WHTQMJltmMTjK5ZfHurUmGPRULzS9KbRxJJRYr7Pn/BoWR6D79RHYXk3aJt
    s3XmfMVDkJF9XMrxYTG3TnfBu4DbkyeeINOoL9ByuI8Z1V79xA36uiHrTTDt+rUj
    3/5FkZUhJfGsOWUgGEe43nTY4/2Zrb4hPKHAvprTjGJb1LRnP4FL84gIZNAP48Xa
    2xz3sRTEXFcbG0qkDgQ=
    -----END CERTIFICATE-----
    
