apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-master-git-ops
  namespace: default
  labels:
    app: app-api-master-git-ops
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api-master-git-ops
  template:
    metadata:
      labels:
        app: app-api-master-git-ops
    spec:
      containers:
      - name: app-api-master-git-ops
        image: imageName
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http